### ISSUE TITLE
Async Tests

### ISSUE THREAD

**Issue by ghost** [k-nasa/ruspec#47]
I'm currently using [#[async_attributes::test]](https://github.com/async-rs/async-attributes) in [my api client](https://github.com/austinsheep/rs-orbit-db-http-client), but would like to use ruspec to write my tests.

Could async tests be performed with ruspec without using `async_std::block_on`?

**Comment by ghost** [comment]
@k-nasa?

**Comment by k-nasa** [comment]
I think that `async_std::test` cannot be used at present. You need to use `block_on`.
It works with such code.
```rust
use async_std::task;
use ruspec::ruspec;

ruspec! {
    describe "test module name" {
        before { let context = 5; }
        subject { context + 5 }

        it "test name" {
            task::block_on( async {
                async fn say_hello() {
                    println!("Hello, world!");
                }

                say_hello().await;
            });

            assert_eq!(subject, 10);
        }
    }
```
