### ISSUE TITLE
Comparison with speculate.rs

### ISSUE THREAD

**Issue by ghost** [k-nasa/ruspec#53]
Hey @k-nasa,

I came across ruspec after seeing [speculate.rs](https://github.com/utkarshkukreti/speculate.rs) is not being actively maintained and does not use syn 1.x as this project does.

A few features from speculate.rs are not available in ruspec at the moment and I was wondering if you planned on adding them:

- Nested context blocks
- Ability to include function attributes for tests such as `#[ignore]` and `#[should_panic]`

**Comment by k-nasa** [comment]
@austinsheep 
I think it's good to deal with them.
But I can't work because I don't have time. Sorry.

PR is welcome.

**Comment by ghost** [comment]
I was playing around with this project, but ended up making a new [testing framework](https://github.com/austinsheep/demonstrate) to more easily incorporate some of the features I was looking for.
